admin_billing-plan:
    resource: "@VeniceAdminBundle/Resources/config/routing/billing-plan.yml"
    type:     yaml

admin_blog-article:
    resource: "@VeniceAdminBundle/Resources/config/routing/blog-article.yml"
    type:     yaml

admin_content:
    resource: "@VeniceAdminBundle/Resources/config/routing/content.yml"
    type:     yaml

admin_dashboard:
    resource: "@VeniceAdminBundle/Resources/config/routing/dashboard.yml"
    type:     yaml

admin_product:
    resource: "@VeniceAdminBundle/Resources/config/routing/product.yml"
    type:     yaml

admin_product-access:
    resource: "@VeniceAdminBundle/Resources/config/routing/product-access.yml"
    type:     yaml

admin_user:
    resource: "@VeniceAdminBundle/Resources/config/routing/user.yml"
    type:     yaml

admin_logger:
    resource: "@VeniceAdminBundle/Resources/config/routing/logger.yml"
    type:     yaml