services:

    admin.listener.menu.config:
        class: Venice\AdminBundle\Services\MenuListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: trinity.main_menu.configure, method: onMenuConfigure }

    knp.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@trinity.admin.menu_builder", createMainMenu]
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.menu, alias: sidebar }

    admin.grid.standardproduct:
        class: Venice\AdminBundle\Grid\ProductGrid
        tags:
          - { name: trinity.grid, alias: standardproduct }

    admin.grid.freeproduct:
        class: Venice\AdminBundle\Grid\ProductGrid
        tags:
          - { name: trinity.grid, alias: freeproduct }

    admin.grid.product:
        class: Venice\AdminBundle\Grid\ProductGrid
        tags:
          - { name: trinity.grid, alias: product }

    admin.grid.content_product:
            class: Venice\AdminBundle\Grid\ContentProductGrid
            tags:
              - { name: trinity.grid, alias: contentproduct }

    admin.grid.user:
        class: Venice\AdminBundle\Grid\UserGrid
        tags:
           - { name: trinity.grid, alias: user }

    admin.grid.product_access:
        class: Venice\AdminBundle\Grid\ProductAccessGrid
        tags:
           - { name: trinity.grid, alias: productaccess }

    admin.grid.billing_plan:
        class: Venice\AdminBundle\Grid\BillingPlanGrid
        tags:
           - { name: trinity.grid, alias: billingplan }

    admin.grid.content:
        class: Venice\AdminBundle\Grid\ContentGrid
        tags:
           - { name: trinity.grid, alias: content }

    admin.grid.group_content:
        class: Venice\AdminBundle\Grid\ContentGrid
        tags:
           - { name: trinity.grid, alias: groupcontent }

    admin.grid.blog_article:
        class: Venice\AdminBundle\Grid\BlogArticleGrid
        tags:
           - { name: trinity.grid, alias: blogarticle }