services:
    # TWIG EXTENSIONS #

    front.twig.extension.render_default_content_template:
        class: FrontBundle\Twig\RenderDefaultContentTemplateExtension
        public: false
        tags:
            - { name: twig.extension }