<?php

namespace Venice\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Trinity\NotificationBundle\Interfaces\NotificationEntityRepositoryInterface;

/**
 * BillingPlanRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BillingPlanRepository extends EntityRepository implements NotificationEntityRepositoryInterface
{
    /**
     * Select entity by id. Set fetch mode to "EAGER" to load all data.
     * todo: possible performance issue...
     *
     * @param $id
     *
     * @return BillingPlan|null
     *
     * @throws NonUniqueResultException
     */
    public function findEagerly($id)
    {
        $query = $this->getEntityManager()->createQuery('
            SELECT bp
            FROM VeniceAppBundle:BillingPlan AS bp
            WHERE bp.id = :id
        ')
            ->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }

    /**
     * Find by product id.
     *
     *
     * @param $id
     *
     * @return BillingPlan[]
     */
    public function findByProductId($id)
    {
        $query = $this->getEntityManager()->createQuery('
              SELECT bp
              FROM VeniceAppBundle:BillingPlan AS bp
              JOIN bp.product product
              WHERE product.id = :id
            ')
            ->setParameter('id', $id);

        return $query->getResult();
    }
}
