<?php

namespace Venice\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * ProductAccessRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProductAccessRepository extends EntityRepository
{
    /**
     * Select entity by id. Set fetch mode to "EAGER" to load all data.
     * todo: possible performance issue...
     *
     * @param $id
     *
     * @return BillingPlan|null
     *
     * @throws NonUniqueResultException
     */
    public function findEagerly($id)
    {
        $query = $this->getEntityManager()->createQuery('
            SELECT pa
            FROM VeniceAppBundle:ProductAccess AS pa
            WHERE pa.id = :id
        ')
            ->setParameter('id', $id);

        return $query->getOneOrNullResult();
    }
}
