services:

    admin.listener.menu.config:
        class: AdminBundle\Services\MenuListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: trinity.main_menu.configure, method: onMenuConfigure }

    knp.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@trinity.admin.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: sidebar }

    admin.form_creator:
        class: AdminBundle\Services\FormCreator
        arguments:
            - "@form.factory"
            - "@router"

    admin.form.custom_collection:
          class: AdminBundle\Form\Collection\CollectionType
          tags:
            - { name: form.type, alias: collection }