parameters:
    locale: en
    bowtie_path: "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/less"
    create_new_entity_on_necktie_notification: true
    app_version: 2.0.0
    necktie_show_product_uri: /admin/product/:id
    necktie_show_user_uri: /admin/user/:id

trinity_notification:
    client:
        drivers: ["trinity.notification.driver.client_api"]
        entity_id_field: necktieId
        server_notify_url: %necktie_url%/api/notify
        server_oauth_url: %necktie_url%/oauth/v2/token
        server_client_id: %necktie_client_id%
        server_client_secret: %necktie_client_secret%
        create_new_entity: %create_new_entity_on_necktie_notification%

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Venice\AppBundle\Entity\User

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'VeniceAdminBundle::formLayout.html.twig'

        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler
        name: vs #venice session
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'VeniceAdminBundle::formLayout.html.twig'
    globals:
        root_path: %kernel.root_dir%
        admin_manager: "@trinity.admin.service.admin_manager"
        appLogic: "@app_logic"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ TrinityAdminBundle, VeniceFrontBundle ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

        lessphp:
            apply_to: "\\.less$"
            # Formatter options: compressed, lessjs, classic
            formatter: "compressed"
            preserve_comments: false
            presets:
                bowtie-less-dir: "\"%bowtie_path%\""
                color-primary: "#493470"
                color-primary-inverse: "#fff"

    assets:
        necktie_ttf:
            inputs:
               - %kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.ttf
            output: "fonts/necktie.ttf"
        necktie_woff:
            inputs:
               - %kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.woff
            output: "fonts/necktie.woff"
        necktie_icons:
           inputs:
              - %kernel.root_dir%/../vendor/modpreneur/bowtie/administration/css/necktie-icons.css
        trinity_eot:
            inputs:
              - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.eot
            output: "fonts/trinity.eot"
        trinity_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.ttf
            output: "fonts/trinity.ttf"
        trinity_woff:
            inputs:
                - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.woff
            output: "fonts/trinity.wof"
        trinity_svg:
            inputs:
                - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.svg
            output: "fonts/trinity.svg"
        ticones_eot:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.eot
            outpoutput: "fonts/tiecons/tiecons.eot"
        ticones_svg:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.svg
            output: "fonts/tiecons/tiecons.svg"
        ticones_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.ttf
            output: "fonts/tiecons/tiecons.ttf"
        ticones_woff:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.woff
            output: "fonts/tiecons/tiecons.woff"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: true
    format_listener: true
    body_listener: true
    view:
        exception_wrapper_handler:  null
        view_response_listener: force
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
        include_format: false
    exception:
        enabled: true
        exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

sensio_framework_extra:
    view:    { annotations: false }

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

white_october_breadcrumbs:
    separator: ''
    viewTemplate: 'VeniceAdminBundle::Breadcrumbs/breadcrumbs.html.twig'

monolog:
    handlers:
        security:
            # log all critical and more important messages
            level:    critical
            type:     stream
            path:     '%kernel.logs_dir%/emergency.log'
            channels:  ~

doctrine_migrations:
    dir_name: src/AppBundle/DoctrineMigrations
    namespace: Venice\AppBundle\DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations

snc_redis:
    # Data are separated on redis databases:
    # default 0 (dev doctrine cache and sessions)
    # 1 (prod doctrine cache)
    # for more see necktie github wiki
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
            logging: false
            options:
                replication: true
    session:
        client: default
        ttl: 3600

trinity_settings:

kms_froala_editor:
    language: "en_gb"
    serialNumber: %froala_editor_key%
    charCounterCount: false
#    pluginsDisabled: does not have an effect
    imageUploadURL: app_froala_upload_image
    fileUploadURL: app_froala_upload_file
    imageManagerDeleteURL: app_froala_delete_image
    imageManagerLoadURL: app_froala_load_images

knp_gaufrette:
    adapters:
        froala_editor_storage:
            aws_s3:
                service_id: app.s3_client
                bucket_name: %amazon_s3_bucket%
                options:
                    create: true
#                    directory: "froala" todo: create a directory for froala files

    filesystems:
        froala_editor_storage:
            adapter:    froala_editor_storage
            alias:      froala_editor_storage_filesystem