parameters:
    locale: en
    bowtie_path: "%kernel.root_dir%/../vendor/modpreneur/bowtie/src/less"
    create_new_entity_on_necktie_notification: true
    app_version: 2.0.0
    necktie_show_product_url: %necktie_url%/admin/product/:id
    necktie_show_user_url: %necktie_url%/admin/user/:id
    necktie_show_product_access_url: %necktie_url%/admin/user/:userId/product-access/:productAccessId
    necktie_show_billing_plan_url: %necktie_url%/admin/product/:productId/billing-plan/:billingPlanId
    trinity.search.detail_url_provider: "trinity.search.detail_url_provider"

trinity_messages:
    sender_identification: "%client_identification%"
    message_user_provider: "@venice.bunny.message_user_provider"
    secret_key_provider: "@venice.app.client_secret_provider"

bunny:
    host: "%rabbit_url%"
    port: "%rabbit_port%"
    vhost: "/"
    user: "%rabbit_user%"
    password: "%rabbit_password%"

    # make heartbeat as long as longest message processing time in any consumer might take
    heartbeat: 120 # in seconds = 2 minutes, default: 60 seconds

trinity_notification:
    drivers: ["trinity.notification.driver.rabbit.client"]
    entity_id_field: necktieId
    entities:
        product: Venice\AppBundle\Entity\Product\StandardProduct
        billing-plan: Venice\AppBundle\Entity\BillingPlan
        user: Venice\AppBundle\Entity\User
        product-access: Venice\AppBundle\Entity\ProductAccess
    mode: client
    client_id: %necktie_client_short_id%
    client_secret_provider: "@venice.app.client_secret_provider"
    forms:
        product: Venice\AppBundle\Form\Notification\ProductType
        billing-plan: Venice\AppBundle\Form\Notification\BillingPlanType
        user: Venice\AppBundle\Form\Notification\UserType
        product-access: Venice\AppBundle\Form\Notification\ProductAccessType

trinity_logger:
    elastic_logs:
        elastic_host: '%elasticsearch_host%'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Venice\AppBundle\Entity\User

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'VeniceAdminBundle::formLayout.html.twig'

        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  snc_redis.session.handler
        name: vs #venice session
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'VeniceAdminBundle::formLayout.html.twig'
    globals:
        root_path: %kernel.root_dir%
        admin_manager: "@trinity.admin.service.admin_manager"
        appLogic: "@venice.app.app_logic"

twig_cache:
    service: trinity.cache

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ TrinityAdminBundle, VeniceFrontBundle ]
    java: /usr/bin/java
    node: /usr/bin/node
    node_paths: [/usr/lib/node_modules]
    filters:
        cssrewrite: ~
        lessphp: ~
    assets:
        necktie_ttf:
            inputs:
               - %kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.ttf
            output: "fonts/necktie.ttf"
        necktie_woff:
            inputs:
               - %kernel.root_dir%/../vendor/modpreneur/bowtie/administration/fonts/necktie.woff
            output: "fonts/necktie.woff"
        necktie_icons:
           inputs:
              - %kernel.root_dir%/../vendor/modpreneur/bowtie/administration/css/necktie-icons.css
        trinity_eot:
            inputs:
              - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.eot
            output: "fonts/trinity.eot"
        trinity_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.ttf
            output: "fonts/trinity.ttf"
        trinity_woff:
            inputs:
                - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.woff
            output: "fonts/trinity.wof"
        trinity_svg:
            inputs:
                - %kernel.root_dir%/../vendor/trinity/admin/AdminBundle/Resources/Public/fonts/trinity.svg
            output: "fonts/trinity.svg"
        ticones_eot:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.eot
            outpoutput: "fonts/tiecons/tiecons.eot"
        ticones_svg:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.svg
            output: "fonts/tiecons/tiecons.svg"
        ticones_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.ttf
            output: "fonts/tiecons/tiecons.ttf"
        ticones_woff:
            inputs:
                - %kernel.root_dir%/../vendor/modpreneur/bowtie/src/fonts/tiecons/tiecons.woff
            output: "fonts/tiecons/tiecons.woff"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    param_fetcher_listener: true
    format_listener: true
    body_listener: true
    view:
        exception_wrapper_handler:  null
        view_response_listener: force
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
        include_format: false
    exception:
        enabled: true
        exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

sensio_framework_extra:
    view:    { annotations: false }

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

white_october_breadcrumbs:
    separator: ''
    viewTemplate: 'VeniceAdminBundle::Breadcrumbs/breadcrumbs.html.twig'

monolog:
    handlers:
        security:
            # log all critical and more important messages
            level:    critical
            type:     stream
            path:     '%kernel.logs_dir%/emergency.log'
            channels:  ~

snc_redis:
    # Data are separated on redis databases:
    # default 0 (dev doctrine cache and sessions)
    # 1 (prod doctrine cache)
    # for more see necktie github wiki
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_dsn%
            logging: false
            options:
                replication: true
    session:
        client: default
        ttl: 3600

trinity_settings:
  settings:
     currency: 'USD'
     items_on_page: 20

kms_froala_editor:
    language: "en_gb"
    serialNumber: %froala_editor_key%
    charCounterCount: false
#    pluginsDisabled: does not have an effect
    imageUploadURL: app_froala_upload_image
    fileUploadURL: app_froala_upload_file
    imageManagerDeleteURL: app_froala_delete_image
    imageManagerLoadURL: app_froala_load_images

knp_gaufrette:
    adapters:
        froala_editor_storage:
            aws_s3:
                service_id: venice.app.s3_client
                bucket_name: %amazon_s3_bucket%
                options:
                    create: true
#                    directory: "froala" todo: create a directory for froala files

    filesystems:
        froala_editor_storage:
            adapter:    froala_editor_storage
            alias:      froala_editor_storage_filesystem