app_api:
    resource: "@VeniceAppBundle/Resources/config/routing/api.yml"
    type:     yaml

app_froala_editor:
    resource: "@VeniceAppBundle/Resources/config/routing/froala-editor.yml"
    type:     yaml

app_necktie:
    resource: "@VeniceAppBundle/Resources/config/routing/necktie.yml"
    type:     yaml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

grid:
  resource: "@GridBundle/Resources/config/routing.yml"
  prefix: "/admin"

fos_user_security_login:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        path: "%login_route%" # route name from parameters
        permanent: true

homepage:
    path: /
    defaults: { _controller: 'VeniceAppBundle:Default:index' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }

public:
    path: /public
    defaults: { _controller: 'VeniceAppBundle:Public:public' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }