app:
    resource: "@AppBundle/Controller"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        path: core_login
        permanent: true

