security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_PAID_USER: ROLE_USER
        ROLE_ADMIN: ROLE_PAID_USER

        ROLE_ADMIN_PRODUCT_VIEW: ROLE_ADMIN
        ROLE_ADMIN_PRODUCT_EDIT: ROLE_ADMIN_PRODUCT_VIEW

        ROLE_ADMIN_CONTENT_VIEW: ROLE_ADMIN
        ROLE_ADMIN_CONTENT_EDIT: ROLE_ADMIN_CONTENT_VIEW

        ROLE_ADMIN_CONTENT_PRODUCT_VIEW: ROLE_ADMIN
        ROLE_ADMIN_CONTENT_PRODUCT_EDIT: ROLE_ADMIN_CONTENT_PRODUCT_VIEW

        ROLE_ADMIN_USER_VIEW: ROLE_ADMIN
        ROLE_ADMIN_USER_EDIT: ROLE_ADMIN_USER_VIEW

        ROLE_ADMIN_BLOG_VIEW: ROLE_ADMIN
        ROLE_ADMIN_BLOG_EDIT: ROLE_ADMIN_BLOG_VIEW

#       see: http://symfony.com/doc/current/cookbook/security/impersonating_user.html
        ROLE_USER_SWITCHER: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN_PRODUCT_EDIT
            - ROLE_ADMIN_CONTENT_EDIT
            - ROLE_ADMIN_CONTENT_PRODUCT_EDIT
            - ROLE_ADMIN_USER_EDIT
            - ROLE_ADMIN_BLOG_EDIT
            - ROLE_USER_SWITCHER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        notify_api:
            pattern: ^/notify/^
            anonymous: true

        main:
            pattern: ^/
            switch_user: true
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
#            remember_me:
#                name: venice_auth
#                lifetime: 31536000 # 365 days in seconds
#                secure: false
#                httponly: true
#                always_remember_me: true
#                key: "%secret%"
            logout:
                success_handler: app.handler.logout_success_handler


    access_control:
        - { path: ^/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-response, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/notify, role: [IS_AUTHENTICATED_ANONYMOUSLY]}
        - { path: ^/*, role: [IS_AUTHENTICATED, IS_AUTHENTICATED_REMEMBERED, IS_AUTHENTICATED_FULLY ]}

