necktie_buy_product:
    path: '/buy/product/{id}/{paySystem}'
    defaults: { _controller: 'Venice\AppBundle\Controller\NecktieBuyController::redirectToNecktieBuy' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }

necktie_thank_you:
    path: '/thank-you'
    defaults: { _controller: 'Venice\AppBundle\Controller\ThankYouController::thankYouAction' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }

necktie_login:
    path: /login
    defaults: { _controller: 'VeniceAppBundle:NecktieLogin:redirectToNecktieLogin' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }

necktie_login_response:
    path: /login-response
    defaults: { _controller: 'VeniceAppBundle:NecktieLogin:processNecktieLoginResponse' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }