ROLE_USER: User
ROLE_PAID_USER: Paid user
ROLE_ADMIN: Admin
ROLE_ADMIN_PRODUCT_VIEW: Product viewer
ROLE_ADMIN_PRODUCT_EDIT: Product editor
ROLE_ADMIN_BILLING_PLAN_VIEW: Billing plan viewer
ROLE_ADMIN_BILLING_PLAN_EDIT: Billing plan editor
ROLE_ADMIN_CONTENT_VIEW: Content viewer
ROLE_ADMIN_CONTENT_EDIT: Content editor
ROLE_ADMIN_CONTENT_PRODUCT_VIEW: Association viewer
ROLE_ADMIN_CONTENT_PRODUCT_EDIT: Association editor
ROLE_ADMIN_USER_VIEW: User viewer
ROLE_ADMIN_USER_EDIT: User editor
ROLE_ADMIN_BLOG_VIEW: Blog viewer
ROLE_ADMIN_BLOG_EDIT: Blog viewer
ROLE_USER_SWITCHER: User switcher
ROLE_SUPER_ADMIN: Super admin