services:

    # SERVICES #

    logic:
         alias: app_logic

    app_logic:
        class: AppBundle\Services\AppLogic
        arguments:
          - "@service_container"
          - true # if bool all methods will return the given bool! leave blank or set to null to ensure default behavior

    app.services.necktie_gateway:
        class: AppBundle\Services\NecktieGateway
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@app.services.necktie_gateway_helper"
            - "@app.services.necktie_connector"
            - %necktie_url%
            - %necktie_client_id%
            - %necktie_client_secret%
            - %login_response_route% #route

    necktie:
        alias: app.services.necktie_gateway

    app.services.necktie_connector:
        class: AppBundle\Services\NecktieConnector

    app.services.necktie_gateway_helper:
        class: AppBundle\Services\NecktieGatewayHelper

    app.services.connection_manager:
        class: AppBundle\Services\ConnectionManager
        arguments:
            - "@service_container"
            - %primary_gateway_service%
            - %secondary_gateway_service%

    form_error_serializer:
        class: AppBundle\Services\FormErrorSerializer

    app.handler.logout_success_handler:
        class: AppBundle\Services\LogoutSuccessHandler
        arguments:
            - %necktie_url%
            - "@router.default"

    app.services.buy_url_generator:
        class: AppBundle\Services\BuyUrlGenerator
        arguments:
            - %necktie_url%
            - "@router"


    # EVENT LISTENERS #

    app.event_listener.kernel_excetpion:
        class: AppBundle\EventListener\KernelExceptionListener
        arguments:
            - "@router"
            - "@service_container"
        tags:
            - {name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException"}

    app.event_listener.free_product_created:
        class: AppBundle\EventListener\AppLogicListener
        arguments:
            - "@doctrine"
        tags:
            - {name: "kernel.event_listener", event: app.free_product_created, method: "onFreeProductCreated"}

    app.entity_listener:
        class: AppBundle\EventListener\EntityListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush}

    # TWIG EXTENSIONS #

    app.twig.extension.human_bool:
        class: AppBundle\Twig\HumanBoolExtension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.date:
         class: Twig_Extensions_Extension_Date
         tags:
             - { name: twig.extension }