services:

    # SERVICES #

    app.services.necktie_gateway:
        class: AppBundle\Services\NecktieGateway
        arguments:
            - @service_container
            - @doctrine.orm.entity_manager
            - @app.services.connector
            - @security.token_storage
            - @router
            - @app.services.necktie_gateway_helper

    necktie:
        alias: app.services.necktie_gateway

    app.services.necktie_gateway_helper:
        class: AppBundle\Services\NecktieGatewayHelper

    app.services.connector:
        class: AppBundle\Services\Connector
        arguments:  [@anchovy.curl]

    app.services.connection_manager:
        class: AppBundle\Services\ConnectionManager
        arguments:
            - @service_container
            - %primary_gateway_service%
            - %secondary_gateway_service%

    app.services.cms_problem_helper:
        class: AppBundle\Services\CMSProblemHelper
        arguments:
            - @service_container
            - %primary_gateway_service%

    form_error_serializer:
        class: AppBundle\Services\FormErrorSerializer


    # EVENT LISTENERS #

    app.event_listener.kernel_excetpion:
        class: AppBundle\EventListener\KernelExceptionListener
        arguments:
            - @router
            - @service_container
        tags:
            - {name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException"}
