services:

    # SERVICES #

    logic:
         alias: app_logic

    app_logic:
        class: AppBundle\Services\AppLogic
        arguments:
          - "@service_container"
          - true # if bool all methods will return the given bool! leave blank or set to null to ensure default behavior

    app.services.necktie_gateway:
        class: AppBundle\Services\NecktieGateway
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@app.services.necktie_gateway_helper"
            - "@app.services.necktie_connector"
            - %necktie_url%
            - %necktie_client_id%
            - %necktie_client_secret%
            - %login_response_route%

    necktie:
        alias: app.services.necktie_gateway

    app.services.necktie_connector:
        class: AppBundle\Services\NecktieConnector

    app.services.necktie_gateway_helper:
        class: AppBundle\Services\NecktieGatewayHelper

    app.services.connection_manager:
        class: AppBundle\Services\ConnectionManager
        arguments:
            - "@service_container"
            - %primary_gateway_service%
            - %secondary_gateway_service%

    form_error_serializer:
        class: AppBundle\Services\FormErrorSerializer

    app.handler.logout_success_handler:
        class: AppBundle\Services\LogoutSuccessHandler
        arguments:
            - "@router.default"
            - %necktie_url%

    app.services.buy_url_generator:
        class: AppBundle\Services\BuyUrlGenerator
        arguments:
            - "@router"
            - %necktie_url%

    admin.form_creator:
        class: AppBundle\Services\FormCreator
        arguments:
            - "@form.factory"
            - "@router"

    # EVENT LISTENERS #

    app.event_listener.kernel_excetpion:
        class: AppBundle\EventListener\KernelExceptionListener
        arguments:
            - "@router"
            - "@service_container"
        tags:
            - {name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException"}

    app.event_listener.free_product_created:
        class: AppBundle\EventListener\AppLogicListener
        arguments:
            - "@doctrine"
        tags:
            - {name: "kernel.event_listener", event: app.free_product_created, method: "onFreeProductCreated"}

    app.entity_listener:
        class: AppBundle\EventListener\EntityListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: onFlush}

    # TWIG EXTENSIONS #

    app.twig.extension.human_bool:
        class: AppBundle\Twig\HumanBoolExtension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.date:
         class: Twig_Extensions_Extension_Date
         tags:
             - { name: twig.extension }


# ************   FORMS   ************

    admin.form.custom_collection:
        class: AppBundle\Form\Collection\CollectionType
        tags:
            - { name: form.type, alias: collection }

    admin.form.content_in_group:
        class: AppBundle\Form\Content\ContentInGroupType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.content_product:
        class: AppBundle\Form\Content\ContentProductType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.group_content:
        class: AppBundle\Form\Content\GroupContentType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.html_content:
        class: AppBundle\Form\Content\HtmlContentType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.mp3_content:
        class: AppBundle\Form\Content\Mp3ContentType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.pdf_content:
        class: AppBundle\Form\Content\PdfContentType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.iframe_content:
        class: AppBundle\Form\Content\IframeContentType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.video_content:
        class: AppBundle\Form\Content\VideoContentType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.free_product:
        class: AppBundle\Form\Product\FreeProductType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.standard_product:
        class: AppBundle\Form\Product\StandardProductType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.user:
        class: AppBundle\Form\User\UserType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.billing_plan:
        class: AppBundle\Form\BillingPlanType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.blog_article:
        class: AppBundle\Form\BlogArticleType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    admin.form.product_access:
        class: AppBundle\Form\ProductAccessType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }