admin_billing_plan_product_index:
    path: '/admin/billing-plan/product/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:index' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_billing_plan_show:
    path: '/admin/billing-plan/show/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:show' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_billing_plan_tabs:
    path: '/admin/billing-plan/tabs/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:tabs' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }

admin_billing_plan_product_set_default:
    path: '/admin/billing-plan/set-default/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:setDefaultBillingPlan' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }

admin_billing_plan_edit:
    path: '/admin/billing-plan/edit/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:edit' }
    requirements: { id: \d+ }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_billing_plan_update:
    path: '/admin/billing-plan/{id}/update'
    defaults: { _controller: 'AdminBundle:BillingPlan:update' }
    requirements: { id: \d+ }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [PUT]

admin_billing_plan_new:
    path: '/admin/billing-plan/new/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:new' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_billing_plan_create:
    path: '/admin/billing-plan/create/{id}'
    defaults: { _controller: 'AdminBundle:BillingPlan:create' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [POST]

admin_billing_plan_delete_tab:
    path: '/admin/billing-plan/tab/{id}/delete'
    defaults: { _controller: 'AdminBundle:BillingPlan:deleteTab' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_billing_plan_delete:
    path: '/admin/billing-plan/{id}/delete'
    defaults: { _controller: 'AdminBundle:BillingPlan:delete' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [DELETE]