admin_user_index:
    path: /admin/user/
    defaults: { _controller: 'AdminBundle:User:index' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_user_show:
    path: '/admin/user/show/{id}'
    defaults: { _controller: 'AdminBundle:User:show' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_user_tabs:
    path: '/admin/user/tabs/{id}'
    defaults: { _controller: 'AdminBundle:User:tabs' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_user_edit:
    path: '/admin/user/edit/{id}'
    defaults: { _controller: 'AdminBundle:User:edit' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_user_update:
    path: '/admin/user/update/{id}'
    defaults: { _controller: 'AdminBundle:User:update' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [PUT]

admin_user_delete_tab:
    path: '/admin/user/tab/{id}/delete'
    defaults: { _controller: 'AdminBundle:User:deleteTab' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_user_delete:
    path: '/admin/user/{id}/delete'
    defaults: { _controller: 'AdminBundle:User:delete' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [DELETE]

admin_user_roles_edit:
    path: '/admin/user/{id}/roles/edit'
    defaults: { _controller: 'AdminBundle:User:rolesEdit' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [GET]

admin_user_roles_update:
    path: '/admin/user/{id}/roles/edit'
    defaults: { _controller: 'AdminBundle:User:rolesUpdate' }
    options: { compiler_class: Symfony\Component\Routing\RouteCompiler }
    methods: [PUT]