Venice\AppBundle\Entity\Content\Content:
    type: entity
    table: content
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        venice_content: Venice\AppBundle\Entity\Content\Content
        venice_groupcontent: Venice\AppBundle\Entity\Content\GroupContent
        venice_htmlcontent: Venice\AppBundle\Entity\Content\HtmlContent
        venice_iframecontent: Venice\AppBundle\Entity\Content\IframeContent
        venice_mp3content: Venice\AppBundle\Entity\Content\Mp3Content
        venice_pdfcontent: Venice\AppBundle\Entity\Content\PdfContent
        venice_videocontent: Venice\AppBundle\Entity\Content\VideoContent
    repositoryClass: Venice\AppBundle\Entity\Repositories\ContentRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: updated_at
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    oneToMany:
        contentProducts:
            targetEntity: Venice\AppBundle\Entity\ContentProduct
            orderBy: { 'orderNumber': 'ASC' }
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: content
            inversedBy: null
            orphanRemoval: false
        contentsInGroup:
            targetEntity: Venice\AppBundle\Entity\Content\ContentInGroup
            orderBy: { 'orderNumber': 'ASC' }
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: content
            inversedBy: null
            orphanRemoval: false
    manyToOne:
        author:
            targetEntity: Venice\AppBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
