Venice\AppBundle\Entity\Content\GroupContent:
    type: entity
    table: content_group
    repositoryClass: Venice\AppBundle\Entity\Repositories\GroupContentRepository
    fields:
        handle:
            type: string
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
    oneToMany:
        items:
            targetEntity: Venice\AppBundle\Entity\Content\ContentInGroup
            orderBy: {'delay': "ASC", 'orderNumber': "ASC"}
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: group
            inversedBy: null
            orphanRemoval: false
            orderBy:
                delay: ASC
                orderNumber: ASC
    lifecycleCallbacks: {  }
