Venice\AppBundle\Entity\Product\Product:
    type: entity
    table: product
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        venice_freeproduct: Venice\AppBundle\Entity\Product\FreeProduct
        venice_standardproduct: Venice\AppBundle\Entity\Product\StandardProduct
    repositoryClass: Venice\AppBundle\Entity\Repositories\ProductRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        handle:
            type: string
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
        image:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        enabled:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        orderNumber:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: order_number
        name:
            type: string
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    oneToMany:
        productAccesses:
            targetEntity: Venice\AppBundle\Entity\ProductAccess
            cascade:
                - remove
            fetch: LAZY
            mappedBy: product
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        contentProducts:
            targetEntity: Venice\AppBundle\Entity\ContentProduct
            orderBy: {'delay': "ASC", 'orderNumber': "ASC"}
            cascade:
                - remove
            fetch: LAZY
            mappedBy: product
            inversedBy: null
            orphanRemoval: false
            orderBy:
                delay: ASC
                orderNumber: ASC
    manyToMany:
        articles:
            targetEntity: Venice\AppBundle\Entity\BlogArticle
            cascade:
                - persist
            fetch: LAZY
            mappedBy: products
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
