Venice\AppBundle\Entity\Product\StandardProduct:
    type: entity
    table: product_standard
    repositoryClass: Venice\AppBundle\Entity\Repositories\StandardProductRepository
    fields:
        necktieId:
            type: integer
            scale: 0
            length: null
            unique: true
            nullable: false
            precision: 0
            column: necktie_id
        purchasable:
            type: boolean
            unique: false
            column: purchasable
        necktieDescription:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0

    oneToMany:
        billingPlans:
            targetEntity: Venice\AppBundle\Entity\BillingPlan
            cascade: {}
            fetch: LAZY
            mappedBy: product
            orphanRemoval: false

    oneToOne:
        necktieDefaultBillingPlan:
            targetEntity: Venice\AppBundle\Entity\BillingPlan
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                necktie_default_billing_plan_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false

        veniceDefaultBillingPlan:
            targetEntity: Venice\AppBundle\Entity\BillingPlan
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                venice_default_billing_plan_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
    lifecycleCallbacks: {  }
