Venice\AppBundle\Entity\User:
    type: entity
    table: user
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: string
    discriminatorMap:
        venice_user: Venice\AppBundle\Entity\User
    repositoryClass: Venice\AppBundle\Entity\Repositories\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        necktieId:
            type: integer
            scale: 0
            length: null
            unique: true
            nullable: true
            precision: 0
            column: necktie_id
        preferredUnits:
            type: string
            scale: 0
            length: 10
            unique: false
            nullable: false
            precision: 0
            column: preferred_units
        birthDate:
            type: date
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: date_of_birth
        locked:
            type: boolean
            unique: false
            column: locked
    oneToMany:
        productAccesses:
            targetEntity: Venice\AppBundle\Entity\ProductAccess
            mappedBy: user
            cascade:
                - remove
                - persist

        OAuthTokens:
            targetEntity: Venice\AppBundle\Entity\OAuthToken
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
