#todo: try to remove fields from trinity
Venice\AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Venice\AppBundle\Entity\Repositories\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        necktieId:
            type: integer
            scale: 0
            length: null
            unique: true
            nullable: true
            precision: 0
            column: necktie_id
        preferredUnits:
            type: string
            scale: 0
            length: 10
            unique: false
            nullable: false
            precision: 0
            column: preferred_units
        birthDate:
            type: date
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: date_of_birth
        status:
            type: array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        firstName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: first_name
        lastName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: last_name
        phoneNumber:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: phone_number
        website:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        avatar:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        public:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        country:
            type: string
            scale: 0
            length: 2
            unique: false
            nullable: true
            precision: 0
        region:
            type: string
            scale: 0
            length: 32
            unique: false
            nullable: true
            precision: 0
        city:
            type: string
            scale: 0
            length: 32
            unique: false
            nullable: true
            precision: 0
        addressLine1:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: address_line1
        addressLine2:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
            column: address_line2
        postalCode:
            type: string
            scale: 0
            length: 10
            unique: false
            nullable: true
            precision: 0
            column: postal_code
    oneToMany:
        productAccesses:
            targetEntity: Venice\AppBundle\Entity\ProductAccess
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy: null
        OAuthTokens:
            targetEntity: Venice\AppBundle\Entity\OAuthToken
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: user
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
