<?php

namespace AppBundle\Entity\Product;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
}
