Venice\AppBundle\Entity\ProductAccess:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - user
                - product
            errorPath: product
        - Symfony\Component\Validator\Constraints\Callback:
            callback: "validate"

#todo: @JakubFajkus causes validation exceptions... need to revalidate the constraint
#    properties:
#        toDate:
#            - Type: \DateTime
#            - GreaterThanOrEqual: "now"