Venice\AppBundle\Entity\ProductAccess:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - user
                - product
            errorPath: product
        - Symfony\Component\Validator\Constraints\Callback:
            callback: "validate"

    properties:
        toDate:
            - Type: \DateTime
            - GreaterThanOrEqual: "now"