Venice\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - email
    properties:
        birthDate:
            - DateTime: ~