Venice\AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields:
                - user
    properties:
        birthDate:
            - DateTime: ~